-- Sistema de Gestão de Pedidos de Alfaiataria — Importação de dados históricos
-- ADITIVO: só insere. Rode DEPOIS do schema_v2.sql.
-- Cada bloco pode ser rodado uma vez só — rodar de novo duplicaria pedidos
-- (os clientes não duplicam, graças ao ON CONFLICT, mas os pedidos/peças sim).

-- ------------------------------------------------------------------
-- 1) Clientes antigos (766 nomes) — cadastro sem pedido vinculado,
--    só para aparecerem no autocomplete e na detecção de recompra.
--    ON CONFLICT ignora quem já existe (comparação case-insensitive).
-- ------------------------------------------------------------------
insert into clientes (nome) values
  ('Abel B. Pereira'),
  ('Addison Ianacio'),
  ('Ademir Dalla Valle'),
  ('Adilson Bueno'),
  ('Adriana Botta'),
  ('Adriano Neuhaus'),
  ('Adroir Da Silva'),
  ('Airton Zarpelon'),
  ('Ajari Rosa Nunes'),
  ('Alan Castelli'),
  ('Alan Mariante Vieira'),
  ('Alberto Kieling'),
  ('Alberto Rosa'),
  ('Alerrandro De Souza'),
  ('Alessandro Rosa'),
  ('Alexander Cramer'),
  ('Alexandre Almeida Verri'),
  ('Alexandre Barreto'),
  ('Alexandre Cidade'),
  ('Alexandre Fish'),
  ('Alexandre Godoy'),
  ('Alexandre Kieslich'),
  ('Alexandre Saltz'),
  ('Alexandre Schuck'),
  ('Alexandre Vellinho'),
  ('Alexandre Zenatti'),
  ('Aline Vanin'),
  ('Allan Da Silva Andres'),
  ('Allan Machado'),
  ('Allan Zambiasi'),
  ('Ana Paula Bernar'),
  ('Anderson Cruz'),
  ('Anderson Freitas Henriques'),
  ('Anderson Lourenz'),
  ('Anderson Medina'),
  ('Anderson Mendes'),
  ('Andre Almeida'),
  ('Andre Cunha'),
  ('Andre Fonseca'),
  ('Andre Godoy'),
  ('Andre Hermann'),
  ('Andre K. Trindade - A. T'),
  ('Andre Luis Da Broi'),
  ('Andre Moreira Silva'),
  ('Andre Rocha Ferreira'),
  ('Andre Roehrs'),
  ('Andreas Mayer'),
  ('Andrei Lazzari'),
  ('Andrew Fanini'),
  ('Andrius Andrin'),
  ('André Maranhão'),
  ('Anelise Maria Engelmann'),
  ('Angelo Da Cas'),
  ('Angelo Passos'),
  ('Antonio Bianchi'),
  ('Antonio Delapieve Neto'),
  ('Antonio Munari'),
  ('Antonio Pandolfo'),
  ('Aristóteles Pires'),
  ('Arthur Alves -'),
  ('Arthur Balcatchuck'),
  ('Arthur Bublitz'),
  ('Arthur Luzardo'),
  ('Arthur Mattos'),
  ('Arthur Oliveira'),
  ('Arthur Sehn'),
  ('Artur Augustin'),
  ('Artur Dombrowski'),
  ('Artur Ting'),
  ('Artur Trapp'),
  ('Aryan Morais'),
  ('Augusto Bastos'),
  ('Augusto Bortolon'),
  ('Augusto Frantz'),
  ('Augusto Loss'),
  ('Augusto Saltiel'),
  ('Babiton Espindola'),
  ('Bernardo Barreiro'),
  ('Bernardo Howes'),
  ('Bernardo Jornada'),
  ('Bernardo Kokemper'),
  ('Bernardo Machado'),
  ('Bernardo Petry'),
  ('Bernardo Schotkis'),
  ('Bili Schneider'),
  ('Bill Scherer'),
  ('Brendon Andrade'),
  ('Bruna Pacheco Da Silveira'),
  ('Bruno Blumm'),
  ('Bruno Boschetti'),
  ('Bruno Burtet'),
  ('Bruno Caravaggio'),
  ('Bruno Fantin'),
  ('Bruno G. Strack'),
  ('Bruno Granvilla'),
  ('Bruno Hoffmeister'),
  ('Bruno Lossio'),
  ('Bruno Oliveira'),
  ('Bruno Rossetto'),
  ('Bruno Scherer'),
  ('Bruno Siliprandi'),
  ('Bruno Strapazzon'),
  ('Bruno Valente'),
  ('Bruno Vargas da Silva'),
  ('Bruno Werner'),
  ('Bryan Theodoro'),
  ('Caio Castro'),
  ('Caio Octave'),
  ('Caio Osorio'),
  ('Caio Raposo'),
  ('Camila Pinto'),
  ('Camillo Alexandretti'),
  ('Candido Mauricio Nuske'),
  ('Carlos Augusto Mostardeiro'),
  ('Carlos Augusto Pereira'),
  ('Carlos Eduardo Pinheiro'),
  ('Carlos Giusti'),
  ('Carlos Henrique'),
  ('Carlos Henrique Brauwers'),
  ('Carlos Henrique D Avila'),
  ('Carlos Junior'),
  ('Carlos Petry Filho'),
  ('Carlos Santos Von Frieling'),
  ('Carlos Scholles'),
  ('Carolina Baldança dos Santos'),
  ('Carolina Mansson'),
  ('Carolina de Oliveira Cavalleiro'),
  ('Caroline Gonçalves'),
  ('Cassiano Konig'),
  ('Cassio De Assis'),
  ('Cassio De Bastiani'),
  ('Cesar Augusto Ritter Carrera'),
  ('Cesar Biasi'),
  ('Cesar Moreno'),
  ('Cesar Pereira de Souza'),
  ('Chalana Reale'),
  ('Charline Ronsoni'),
  ('Christian Oliveira'),
  ('Claudia Ribeiro'),
  ('Claudio Martins'),
  ('Clinty Riw Da Rosa'),
  ('Conrado Lima'),
  ('Cristiane Soares'),
  ('Cristiano Bidinha'),
  ('Cristiano Lindenmeyer'),
  ('Cristiano Souza'),
  ('Cynthia Faveiro'),
  ('Daniel Amaral'),
  ('Daniel Araujo'),
  ('Daniel Becker'),
  ('Daniel Biolo'),
  ('Daniel Bueno'),
  ('Daniel Fernandes'),
  ('Daniel Jesus'),
  ('Daniel Sant'),
  ('Daniel Santos'),
  ('Daniel Simão'),
  ('Daniel Zanotto'),
  ('Danielle Debom'),
  ('David Brusque'),
  ('Daviel Junior Luz'),
  ('Debora Moraes'),
  ('Decio Becker'),
  ('Diana Godinho'),
  ('Diego Camiza'),
  ('Diego Gauto'),
  ('Diego Goulart'),
  ('Diego Leonardo de Oliveira'),
  ('Diego Lourenzi'),
  ('Diego Luft'),
  ('Diego Pertile Borges'),
  ('Diego Veiga'),
  ('Dieison Silva'),
  ('Dierson Richetti'),
  ('Dinar Fernandes'),
  ('Dionata Rodrigues dos Santos'),
  ('Douglas Feijo -'),
  ('Douglas Martello'),
  ('Douglas Salvador'),
  ('Douglas Schreiner'),
  ('Douglas de Oliveira Wilgies'),
  ('Eder Fontana'),
  ('Edgar Serrano'),
  ('Edson Rodrigo Muck'),
  ('Eduardo Ahlert'),
  ('Eduardo Araujo'),
  ('Eduardo Arcaro'),
  ('Eduardo Assmann'),
  ('Eduardo Aumann'),
  ('Eduardo Beleske'),
  ('Eduardo Boesing'),
  ('Eduardo Bordin'),
  ('Eduardo Brasil'),
  ('Eduardo Citolin'),
  ('Eduardo Dias Dos Santos'),
  ('Eduardo Fochesatto'),
  ('Eduardo Francesquet'),
  ('Eduardo Fulginiti De Assis'),
  ('Eduardo Gonçalves Spitaliere'),
  ('Eduardo Lopes Mostardeiro'),
  ('Eduardo Marocke'),
  ('Eduardo Moraes'),
  ('Eduardo Oliveira Pereira'),
  ('Eduardo Onzi'),
  ('Eduardo Petersen'),
  ('Eduardo Pinzetta'),
  ('Eduardo Saraiva Da Cunha'),
  ('Eduardo Schuler'),
  ('Eduardo Segatto'),
  ('Elder Peretti'),
  ('Eliandro Da Rocha Mendes'),
  ('Eloi Dias Dos Santos'),
  ('Emerson Barros'),
  ('Emerson Matheos'),
  ('Emerson Mendes'),
  ('Emerson Milano'),
  ('Enrico Bellini'),
  ('Enzo Binotto'),
  ('Eric Damiani Meyer'),
  ('Eric Morais'),
  ('Eric kudiess'),
  ('Erik Leopoldo'),
  ('Evandro Luft'),
  ('Evandro Tarciuk'),
  ('Evelyn Tirado Padilha'),
  ('Everton Fraga'),
  ('Everton Moreto'),
  ('Ezequiel Dartora'),
  ('Fabian Silva'),
  ('Fabiano Doca'),
  ('Fabiano Pontin'),
  ('Fabiano Rihan'),
  ('Fabio Aurelio Jorge'),
  ('Fabio Olson'),
  ('Fabiola Ajnhorn'),
  ('Fabiola Radaelli'),
  ('Fabricio Ferreira'),
  ('Fabricio Mattos'),
  ('Fabricio Neis'),
  ('Fabricio Ritter'),
  ('Felipe Brack'),
  ('Felipe Cardoso'),
  ('Felipe Daniel Gomes'),
  ('Felipe De Bacco'),
  ('Felipe Franchi'),
  ('Felipe Friedrich'),
  ('Felipe Hausen'),
  ('Felipe Lopes Trois'),
  ('Felipe Mallmann'),
  ('Felipe Malmann'),
  ('Felipe Maroco de Borba'),
  ('Felipe Martini'),
  ('Felipe Mattione'),
  ('Felipe Mezzomo'),
  ('Felipe Moraes'),
  ('Felipe Nicola'),
  ('Felipe Pires'),
  ('Felipe Schuster'),
  ('Felipe Stechman Drebes'),
  ('Fellipe Rizzitto'),
  ('Fernanda Osorio'),
  ('Fernando Araújo'),
  ('Fernando Bagattini'),
  ('Fernando Brum'),
  ('Fernando Campos de Castro'),
  ('Fernando Martins Costa'),
  ('Fernando Parisotto'),
  ('Fernando Rizzo'),
  ('Fernando Theodoro Sehnem'),
  ('Fernando Vendramin'),
  ('Filipe Rosa'),
  ('Filipe de Almeida Dias'),
  ('Flavio Ordoque'),
  ('Flavio Schutt'),
  ('Flavio Wenning'),
  ('Frederico Braga'),
  ('Frederico Monteiro'),
  ('Gabriel Andrade'),
  ('Gabriel Berte - Peito G. B'),
  ('Gabriel Bonelli'),
  ('Gabriel Ferro'),
  ('Gabriel Franke'),
  ('Gabriel Hocevar'),
  ('Gabriel Lourenço'),
  ('Gabriel Malisca'),
  ('Gabriel Maria'),
  ('Gabriel Roman'),
  ('Gabriel Ross'),
  ('Gabriel Santos'),
  ('Gabriel de Carvalho'),
  ('Gabriela S. Moreira'),
  ('Gabriela Scherer'),
  ('Gean Salazar'),
  ('Gelson Araujo'),
  ('Gelson Garcez'),
  ('Geovane Rodrigues Bordini'),
  ('Geovany Santos'),
  ('Geraldo Vargas'),
  ('Germano Barboza'),
  ('Germano Saltiel'),
  ('Getulio Escopelli'),
  ('Gilmar Duarte'),
  ('Gilmar Stelo'),
  ('Gilson Valandro'),
  ('Giordano De Almeida'),
  ('Giovani Bina'),
  ('Giovani De Cesaro'),
  ('Giovani Ferreira Gnoatto'),
  ('Giovani Silveira Fialho'),
  ('Giovanni Brum'),
  ('Giuliano Deboni'),
  ('Giuseppe Valente'),
  ('Glauber Witt'),
  ('Gonzalo Rodriguez'),
  ('Graciela Justo'),
  ('Gregori Fronza'),
  ('Gregorio Antonio Arnecke'),
  ('Guilherme Abreu'),
  ('Guilherme Bassols'),
  ('Guilherme Bertotto'),
  ('Guilherme Bohrer'),
  ('Guilherme Bulegon'),
  ('Guilherme Caetano Mendes'),
  ('Guilherme Capelari'),
  ('Guilherme De Castro Perussolo'),
  ('Guilherme De Souza Pedroso'),
  ('Guilherme Fontanela de Carvalho'),
  ('Guilherme Franzen Rizzo'),
  ('Guilherme Gobetti'),
  ('Guilherme Ioris'),
  ('Guilherme Luis Fernandes'),
  ('Guilherme Mendes Ribeiro'),
  ('Guilherme Michaelsen'),
  ('Guilherme Moretto'),
  ('Guilherme Nozari'),
  ('Guilherme Nunes'),
  ('Guilherme Pedo Vens'),
  ('Guilherme Rocha da Rocha'),
  ('Guilherme Rotuno'),
  ('Guilherme Schaurich da Silva'),
  ('Guilherme Tarrago'),
  ('Guilherme Trevisan'),
  ('Guilherme Vargas'),
  ('Guilherme Venturin'),
  ('Guilherme Xavier'),
  ('Gustavo Arnecke'),
  ('Gustavo Bender'),
  ('Gustavo Brum'),
  ('Gustavo De Medeiros'),
  ('Gustavo Dutra'),
  ('Gustavo Ferreira'),
  ('Gustavo Koundhadjian'),
  ('Gustavo Mahr'),
  ('Gustavo Prade -'),
  ('Gustavo Scalamato Reus'),
  ('Gustavo Schneider'),
  ('Gustavo Vearick'),
  ('Halisson Souza'),
  ('Haroldo Monteiro'),
  ('Heitor Rodrigues'),
  ('Heleno Garay'),
  ('Henrique Almeida'),
  ('Henrique Avendano'),
  ('Henrique Nunes'),
  ('Henrique Paluszkiewicz'),
  ('Henrique Silveira'),
  ('Henrique Thomé'),
  ('Hercules Perrone'),
  ('Hugo Cunha'),
  ('Humberto Rocha'),
  ('Iago Giacomeli'),
  ('Igor Flores'),
  ('Igor Martins'),
  ('Igor Mota'),
  ('Ingrid Somacal'),
  ('Italo Benedetti'),
  ('Iuri Zanon'),
  ('Ivan Petry'),
  ('Ivan Rocha - I. R'),
  ('JAPA - Monograma Punho C. Y'),
  ('Jackson Oliveira'),
  ('Jaime Mattos'),
  ('Jair Neis'),
  ('Jean Bittencourt'),
  ('Jeferson Dutra'),
  ('Jefferson Pizzio'),
  ('Jeronimo Peres Ramos'),
  ('Jhonatan Nascimento'),
  ('Joao Bertoto'),
  ('Joao Pedro Nogueira'),
  ('Joao Vicente Laste Rodenbusch'),
  ('Jocel Gadens'),
  ('Johann Bicca'),
  ('Jonas Halmens'),
  ('Jonas Rocha Cardozo'),
  ('Jonas Tolotti'),
  ('Jonas Venturini'),
  ('Jordan Torma'),
  ('Jose Carlos'),
  ('Jose Motta'),
  ('Jose Roque Persch'),
  ('Josias Bento Da Rosa'),
  ('Josiel Rocha De Souza'),
  ('João Back'),
  ('João Batista Nunes'),
  ('João Cernicchiaro'),
  ('João Claudio Sidou'),
  ('João Flores'),
  ('João Lucas Ferraz'),
  ('João Marcelo Ugalde'),
  ('João Pedro Baldi'),
  ('João Pedro Clemente'),
  ('João Pedro Pacheco'),
  ('João Pedro Rosa'),
  ('João Ricardo Kist'),
  ('João Venter'),
  ('João Vicente'),
  ('João Vicente Sidou'),
  ('João Victor'),
  ('João Victor Eguia'),
  ('Julia Dos Santos Costa'),
  ('Julia Schutt'),
  ('Julia Silva de Souza'),
  ('Juliana Leopardo'),
  ('Juliano Alexandre'),
  ('Juliano De Angelis'),
  ('Juliano Dias'),
  ('Juliano Lauer'),
  ('Juliano Otton'),
  ('Juliano Souza'),
  ('Julio Brandão'),
  ('Junior Costa'),
  ('Junior Rodrigues'),
  ('Karane Viera'),
  ('Kyrion Mello'),
  ('Laerte De Andrade'),
  ('Lafayete Josué Barth'),
  ('Laura Flores'),
  ('Layon Stoffels'),
  ('Laís Evangelista Travi'),
  ('Leandro Eckhardt'),
  ('Leandro Garbin'),
  ('Leandro Nunes'),
  ('Leandro Rosa'),
  ('Lediel Santos'),
  ('Leonardo Abreu'),
  ('Leonardo L. Paim'),
  ('Leonardo Lima'),
  ('Leonardo Yamachita'),
  ('Leonardo Zambiasi'),
  ('Lisandro Jacobs'),
  ('Lisiane Oliveira'),
  ('Livia Otto Saffi'),
  ('Lorenzo Minetto Araujo'),
  ('Luan Fontanella'),
  ('Lucas Buffon'),
  ('Lucas Dornelles'),
  ('Lucas Ferraz'),
  ('Lucas Forner'),
  ('Lucas Golbert'),
  ('Lucas Jacoby'),
  ('Lucas Leiva'),
  ('Lucas Mello Dos Santos'),
  ('Lucas Oliveira Costa'),
  ('Lucas Rech'),
  ('Lucas Sombrio'),
  ('Lucas Stocker'),
  ('Lucca Bica'),
  ('Lucca Marrone'),
  ('Luciano Forni'),
  ('Luciano Hillesheim'),
  ('Luigi Ligabue'),
  ('Luis Augusto Camargo'),
  ('Luis Felipe Rossi'),
  ('Luis Fernando Salet'),
  ('Luis Paulo Andrioni'),
  ('Luis Schroer'),
  ('Luiz Fernando Vargas'),
  ('Luiz Guilherme Esch'),
  ('Luiz Henrique Haselein'),
  ('Luiz Krug'),
  ('Luiz Roberto -'),
  ('Luiza Albanese'),
  ('Maiquel Vargas'),
  ('Manoel Bacellar'),
  ('Manoel Correa'),
  ('Manuela Padilha'),
  ('Marcel Rodrigues'),
  ('Marcelo Casagrande'),
  ('Marcelo Citadim'),
  ('Marcelo Duquia'),
  ('Marcelo Endres'),
  ('Marcelo Guaragni'),
  ('Marcelo Ilhesca'),
  ('Marcelo Pereira'),
  ('Marcelo Pizzato'),
  ('Marcelo do Santos Moreira'),
  ('Marcio Boni'),
  ('Marcio Pizzato'),
  ('Marclei Luzardo'),
  ('Marco Antonio - Peito M. A. R'),
  ('Marco Costa'),
  ('Marco Felipe Assunção'),
  ('Marco Meira'),
  ('Marco Nery'),
  ('Marcos Felipe Meneguetti'),
  ('Marcos Kosminsky'),
  ('Marcos Krausburg Araujo'),
  ('Marcos Pablo'),
  ('Marcus Cunha'),
  ('Maria Bastos'),
  ('Mariju Maciel'),
  ('Marilia Toson'),
  ('Marina Alquati da Silva'),
  ('Marino Rossi'),
  ('Marlon Bernard'),
  ('Martin'),
  ('Martin Hauser'),
  ('Mateus Amaral'),
  ('Mateus Ferreira'),
  ('Mateus Galetto'),
  ('Mateus Gribov'),
  ('Mateus Marques'),
  ('Matheo Moroni'),
  ('Matheus Alencar'),
  ('Matheus Bialeski Gomes'),
  ('Matheus Caleffi'),
  ('Matheus Dalmolin'),
  ('Matheus Gonzales'),
  ('Matheus Henrique De Souza Oliveira'),
  ('Matheus Paz'),
  ('Matheus Souza Moises'),
  ('Matheus Teixeira Netto'),
  ('Mathias Heineck'),
  ('Mathias Nougueira'),
  ('Mathias Villasanti'),
  ('Matias Gerhardt'),
  ('Mauricio Bedatti'),
  ('Mauricio Canabarro'),
  ('Mauricio Costa Rodrigues'),
  ('Mauricio Cristal'),
  ('Mauricio Noll'),
  ('Mauricio Tavares de Almeida'),
  ('Mauricio Xavier Tavares'),
  ('Mauricio de Castro'),
  ('Mauro Conte'),
  ('Maurício Antonio Bordignon'),
  ('Maurício Collet Romanini'),
  ('Maycon Leite'),
  ('Michel Azeredo'),
  ('Michel Gomes'),
  ('Michel Lehugeur'),
  ('Michele Scaranto'),
  ('Michele Zat'),
  ('Miguel Darzé'),
  ('Miguel Prado'),
  ('Miguel Santos'),
  ('Miguel Scarpellini Mattos'),
  ('Milene Schimidt'),
  ('Misael Costa'),
  ('Murilo Davila'),
  ('Mário Antônio Rodrigues Da Silveira'),
  ('Nadison Hax'),
  ('Nathan Da Silva Andres'),
  ('Nelson Dell'),
  ('Nelson Zimmermann'),
  ('Nicolas Gass'),
  ('Nicolas Lipp'),
  ('Nicolas Rabaiolli'),
  ('Nicole Farias'),
  ('Nicolle Muratori Wilhelm'),
  ('Norberto Farias'),
  ('Odilson Zoti'),
  ('Otavio Bauer'),
  ('Patricia Bitello'),
  ('Paula La Rocca'),
  ('Paulo Custodio'),
  ('Paulo Dantas'),
  ('Paulo Dutra'),
  ('Paulo Eduardo De Andrade Rouffiax'),
  ('Paulo Fayet'),
  ('Paulo Henrique Martins'),
  ('Paulo Henrique Ruschel'),
  ('Pedro Aranalde Fabricio'),
  ('Pedro Braun'),
  ('Pedro Costa'),
  ('Pedro Dornelles'),
  ('Pedro Gomes'),
  ('Pedro Gonçalves'),
  ('Pedro Hilário'),
  ('Pedro Jose Neves Melo'),
  ('Pedro Morais'),
  ('Pedro Santos'),
  ('Pedro Velasco'),
  ('Pedro Vescovi'),
  ('QT'),
  ('Rafael Benedeti'),
  ('Rafael Carissimi'),
  ('Rafael Correa'),
  ('Rafael Dutra'),
  ('Rafael Fernandes Oliveira'),
  ('Rafael Gutterres'),
  ('Rafael Klaus Krummenauer'),
  ('Rafael Lenhart Vaccaro'),
  ('Rafael Martins Costa'),
  ('Rafael Mejias'),
  ('Rafael Mitidieri Gomes'),
  ('Rafael Ortiz'),
  ('Rafael Panonko'),
  ('Rafael Rosa'),
  ('Rafael Santos'),
  ('Rafael Saraiva'),
  ('Rafael Sperotto'),
  ('Rafael Tissot'),
  ('Rafael Tonding'),
  ('Rafaela Frare'),
  ('Raian Ferreira'),
  ('Rakel Miorando'),
  ('Ramiro Assaf Padilla'),
  ('Ramiro Ferreira'),
  ('Ramon Molnar Ilha'),
  ('Raul Birgesch'),
  ('Raul Mendonça Rodrigue'),
  ('Raul Rossi'),
  ('Regis Correa'),
  ('Renan Aramburu'),
  ('Renan Frizzo'),
  ('Renan Prestes'),
  ('Renato Nahas'),
  ('Renzo Vespa'),
  ('Ricardo Andre de Oliveira'),
  ('Ricardo Aquino'),
  ('Ricardo Dornelles'),
  ('Ricardo Ferreira'),
  ('Ricardo Fischer'),
  ('Ricardo Leal'),
  ('Ricardo Luiz De Almeida'),
  ('Ricardo Matte'),
  ('Ricardo Mazzuca'),
  ('Ricardo Menalda'),
  ('Ricardo Raffin'),
  ('Ricardo Schuree'),
  ('Roberta Dalle Molle'),
  ('Roberto Alvim'),
  ('Roberto Majo'),
  ('Roberto Risk'),
  ('Roberto da Cruz Brenol'),
  ('Robson Casagrande'),
  ('Robson Lima'),
  ('Robson Scorsatto'),
  ('Rodolfo Agostini'),
  ('Rodolfo Urruth'),
  ('Rodolfo Weumann'),
  ('Rodrigo Alano'),
  ('Rodrigo Azevedo - Punho R. A'),
  ('Rodrigo Bertoline'),
  ('Rodrigo Brauch Cobertta'),
  ('Rodrigo Buhler'),
  ('Rodrigo Dalegrave'),
  ('Rodrigo Fantinel'),
  ('Rodrigo Feix'),
  ('Rodrigo Fernandes'),
  ('Rodrigo Ferreira De Souza'),
  ('Rodrigo Fleck'),
  ('Rodrigo Heffner'),
  ('Rodrigo Klemmetich'),
  ('Rodrigo Lisboa'),
  ('Rodrigo Machado'),
  ('Rodrigo Montini'),
  ('Rodrigo Paim'),
  ('Rodrigo Pureza'),
  ('Rodrigo Ruschel'),
  ('Rodrigo Stiehl'),
  ('Rodrigo Veiga'),
  ('Rodrigo Zamboni'),
  ('Rodrigo Zarichta'),
  ('Rogerio Aime'),
  ('Rogerio Arthur Matos'),
  ('Rogerio Batista'),
  ('Rolf Madaleno'),
  ('Romulo Dos Santos Pozzebom'),
  ('Ronaldo Delevati'),
  ('Ronicler Guimaraes Da Leve'),
  ('Ronildo da Silva'),
  ('Rubem Knjinik Lucion'),
  ('Rudolf Macedo'),
  ('Ruy Costa Neto'),
  ('Ruy Maranhão'),
  ('Samuel De Bona'),
  ('Samuel Volpi'),
  ('Samuel da Rosa Andrade'),
  ('Sergio Roberto Loureiro'),
  ('Sergio Venero'),
  ('Taiguar Araujo'),
  ('Tales Schmidt'),
  ('Tarso Hoffmeister'),
  ('Tassio Terres -'),
  ('Taís Maia'),
  ('Teo Borges'),
  ('Thais Mosh'),
  ('Thales Gralha'),
  ('Thiago Fagundes -'),
  ('Thiago Freitas'),
  ('Thiago Frizzo'),
  ('Thiago Hoffmann'),
  ('Thiago Lehr'),
  ('Thiago Lunardi'),
  ('Thiago Pereyra'),
  ('Thiago Silveira'),
  ('Thiago V. Martin - Punho T. V. M'),
  ('Thiago Valverde'),
  ('Thomas Cesa'),
  ('Thomas Sirotsky'),
  ('Thomaz Silva'),
  ('Tiago Antolini'),
  ('Tiago Blaya Martins'),
  ('Tiago Camino'),
  ('Tiago Cirne'),
  ('Tiago Cruz'),
  ('Tiago Cury'),
  ('Tiago Faria'),
  ('Tiago Giordani Camicia'),
  ('Tiago Morão'),
  ('Tiago Silva'),
  ('Tobias Skrebsky de Almeida'),
  ('Tomas Afonso Demenech Guerra'),
  ('Tomas Fernandes'),
  ('Tomas Rossi'),
  ('Tomás Ferro'),
  ('Tumauy Cabral'),
  ('Ubiratan Benedetti'),
  ('Vanessa Ortiz'),
  ('Vicente Costa'),
  ('Vicente Raguzzoni'),
  ('Vicente Scopel'),
  ('Victor Antonio'),
  ('Victor Pinho'),
  ('Victoria Furtado Badin'),
  ('Vilhiam H. dos Santos -'),
  ('Vinicius Bock'),
  ('Vinicius Fraga'),
  ('Vinicius Gazzi'),
  ('Vinicius Malta Martins'),
  ('Vinicius Nader'),
  ('Vinicius Nunes'),
  ('Vinicius Prates'),
  ('Vinicius Rodrigues'),
  ('Vinicius Zandona'),
  ('Vitor Aguiar'),
  ('Vitor Bicca'),
  ('Vitor Borges'),
  ('Vitor Mattos'),
  ('Vitor Montes'),
  ('Vladimir Bertiz'),
  ('Volmir Barbieri Junior'),
  ('Volmir Colla'),
  ('Wagner Couto'),
  ('Wagner Figueiredo'),
  ('Walter Barcelos'),
  ('Welington Boito'),
  ('William Bitencourt'),
  ('William Bueno'),
  ('William May'),
  ('William Trinca'),
  ('Willian Andriguetti Da Silva'),
  ('Yane Martins')
on conflict (nome_normalizado) do nothing;

-- ------------------------------------------------------------------
-- 2) Peças já produzidas pelo Icaro (29 registros) -> pedidos_alfaiataria.
--    Cria o cliente se ainda não existir (mesma regra de nome_normalizado).
-- ------------------------------------------------------------------
with dados (cliente_nome, tipo_peca, valor_total, valor_pago, obs) as (
  values
  ('Tiago Cury', 'Costume', 1000.00, 1000.00, null),
  ('Marcio Pizzato', 'Blazer', 800.00, 800.00, 'Peça original (planilha antiga): Blazer Lã'),
  ('Felipe Franchi', 'Calça', 200.00, 200.00, 'Peça original (planilha antiga): Calça off White'),
  ('Felipe Trois', 'Costume', 1000.00, 1000.00, null),
  ('Lucas Jacobs', 'Calça', 200.00, 200.00, null),
  ('Lucas Jacobs', 'Calça', 200.00, 200.00, null),
  ('Tales Schuck', 'Traje', 1000.00, 1000.00, null),
  ('Artur Trapp', 'Costume', 1000.00, 500.00, null),
  ('Douglas Schreiner', 'Costume', 1000.00, 500.00, null),
  ('Daniel Sant', 'Traje', 1000.00, 500.00, null),
  ('Tales Schuck', 'Casaco', 1000.00, 1000.00, 'Peça original (planilha antiga): Casaco Lã'),
  ('Rogerio Aime', 'Costume', 1000.00, 500.00, null),
  ('Eduardo Mostardeiro', 'Traje', 1000.00, 500.00, null),
  ('Carlos Augusto Mostardeiro', 'Costume', 1000.00, 500.00, null),
  ('Andre Trindade', 'Costume', 1000.00, 500.00, null),
  ('Marcus Cunha', 'Costume', 1000.00, 500.00, null),
  ('Gabriel De Carvalho', 'Traje', 1000.00, 500.00, null),
  ('Marcus Cunha', 'Costume', 1000.00, 500.00, null),
  ('Lucas Jacobs', 'Bomber', 500.00, 100.00, null),
  ('Felipe Trois', 'Traje', 1000.00, 500.00, null),
  ('Felipe Trois', 'Calça', 200.00, 200.00, null),
  ('Felipe Trois', 'Calça', 200.00, 200.00, null),
  ('Felipe Trois', 'Calça', 200.00, 200.00, null),
  ('Alerrandro De Souza', 'Traje', 1000.00, 500.00, null),
  ('Felipe De Bacco', 'Costume', 1000.00, 500.00, null),
  ('Felipe De Bacco', 'Calça', 200.00, 200.00, null),
  ('Felipe De Bacco', 'Calça', 200.00, 0.00, null),
  ('Assis Idemar', 'Costume', 1000.00, 0.00, null),
  ('Ricardo Schuree', 'Calça', 200.00, 0.00, null)
),
clientes_novos as (
  insert into clientes (nome)
  select distinct cliente_nome from dados
  on conflict (nome_normalizado) do nothing
  returning id, nome
)
insert into pedidos_alfaiataria (cliente_id, tipo_peca, valor_total, valor_pago, observacoes)
select c.id, d.tipo_peca, d.valor_total, d.valor_pago, d.obs
from dados d
join clientes c on c.nome_normalizado = lower(trim(d.cliente_nome));

-- ------------------------------------------------------------------
-- 3) Pendências de pagamento à Fabiana (12 clientes) -> pedidos (camisas).
--    Valor cobrado do cliente não constava na planilha (só o status de
--    recebimento) — valor_receber fica em branco, mas o status de
--    recebimento e o valor pendente à Fabiana são importados.
--    Plano de assinatura marcado quando a quantidade total é maior que
--    a quantidade já entregue (entrega parcial em andamento).
-- ------------------------------------------------------------------
with dados (cliente_nome, quantidade, status, qt_entregue, status_receber, valor_fabiana, plano_assinatura) as (
  values
  ('Rodolfo Agostini', 3, 'Prova', 1, 'Recebido', 240.00, true),
  ('Julia Silva de Souza', 2, 'Prova', 1, 'Recebido', 120.00, true),
  ('Marcus Cunha', 5, 'Prova', 1, 'Recebido', 480.00, true),
  ('Rafael Mejias', 3, 'Prova', 1, 'Recebido', 240.00, true),
  ('Andrius Endrigo Andrin', 1, 'Entregue', 1, 'Recebido', 120.00, false),
  ('Welington Boito', 2, 'Prova', 1, 'Recebido', 120.00, true),
  ('Cristiano Lindenmeyer', 3, 'Prova', 1, 'Recebido', 240.00, true),
  ('Daniel Becker', 5, 'Prova', 1, 'Recebido', 480.00, true),
  ('Willian Bitencourt', 4, 'Prova', 1, 'Recebido', 360.00, true),
  ('Cesar Moreno', 4, 'Prova', 1, 'Recebido', 360.00, true),
  ('Raul Mendonça Rodrigues', 2, 'Prova', 1, 'Recebido', 120.00, true),
  ('Rentato Nahas', 6, 'Prova', 1, 'Recebido', 600.00, true)
),
clientes_novos as (
  insert into clientes (nome)
  select distinct cliente_nome from dados
  on conflict (nome_normalizado) do nothing
  returning id, nome
)
insert into pedidos (
  cliente_id, quantidade, status, qt_entregue,
  status_pagamento_receber, valor_pago_fabiana, status_pagamento_fabiana,
  plano_assinatura, observacoes
)
select
  c.id, d.quantidade, d.status, d.qt_entregue,
  d.status_receber, d.valor_fabiana, 'Pendente',
  d.plano_assinatura,
  'Importado da planilha antiga de pendências (data do pedido original não informada).'
from dados d
join clientes c on c.nome_normalizado = lower(trim(d.cliente_nome));
